
-- DROP TABLE IF EXISTS Incident;
-- DROP TABLE IF EXISTS Incident_type;
-- DROP TABLE IF EXISTS Location;
-- DROP TABLE IF EXISTS Users;

CREATE TABLE IF NOT EXISTS Users (
  id    INTEGER PRIMARY KEY AUTOINCREMENT,
  name  TEXT NOT NULL,
  email TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS Incident_type (
  code INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Location (
  id   INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Incident (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id     INTEGER NOT NULL,
  inc_code    INTEGER NOT NULL,
  description TEXT,
  created_at  TEXT NOT NULL,
  status      TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN','ASSIGNED','WAITING_REPLY','CLOSED')),
  location_id INTEGER NULL,
  FOREIGN KEY (user_id)  REFERENCES Users(id)          ON DELETE RESTRICT,
  FOREIGN KEY (inc_code) REFERENCES Incident_type(code) ON DELETE RESTRICT,
  FOREIGN KEY (location_id) REFERENCES Location(id)     ON DELETE RESTRICT
);
